add missing <li> tag in navigation list
everypolitician/everypolitician-docs pull request #24
Opened 2016-09-13 10:09 UTC by davewhiteland

Spotted our markup was missing an initial <li> in the navigation. This fixes it.

2016-09-13 10:11 UTC, davewhiteland commented
Sanity check/review from any of the team welcome :-)

2016-09-14 20:32 UTC, tmtmtmtm requested changes
Travis is broken; this is going to need a `bundle install` first.

2016-09-14 20:40 UTC, tmtmtmtm approved these changes

2016-09-15 11:38 UTC, chrismytton commented
Rebased onto the latest `gh-pages`.

2016-09-15 15:22 UTC, tmtmtmtm commented
And another rebase post #31

2016-09-15 15:48 UTC, merged